//go:build ignore

// gen_npm_versions reads the top-level and npm lockfiles to capture
// the actual installed versions of npm dependencies, then writes
// npm_versions.go which registers them at init time.
// Run via: go generate ./cmd/workiq-proxy/
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"
	"time"
)

// lockfileV3 matches the npm lockfile v3 format where all resolved
// versions live under "packages"."node_modules/<name>".
type lockfileV3 struct {
	Packages map[string]struct {
		Name    string `json:"name"`
		Version string `json:"version"`
	} `json:"packages"`
}

type packageJSON struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// resolvedVersions reads a package-lock.json and returns a map of
// package name → installed version for every resolved dependency.
func resolvedVersions(path string) (map[string]string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var lf lockfileV3
	if err := json.Unmarshal(data, &lf); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	out := make(map[string]string)
	for key, pkg := range lf.Packages {
		// The root entry has key "" — skip it.
		if key == "" {
			continue
		}
		// Extract the package name from the path. Nested
		// node_modules (e.g. "node_modules/a/node_modules/b")
		// use the last segment. For scoped packages the name
		// includes the scope (e.g. "@eslint/js").
		parts := strings.Split(key, "node_modules/")
		name := parts[len(parts)-1]
		if name == "" {
			continue
		}
		// Keep the first (shallowest) resolution for each name.
		if pkg.Version != "" {
			if _, exists := out[name]; !exists {
				out[name] = pkg.Version
			}
		}
	}
	return out, nil
}

func main() {
	type entry struct {
		Name    string
		Version string
	}
	var entries []entry

	// npm package's own identity from npm/package.json.
	if data, err := os.ReadFile("../../npm/package.json"); err == nil {
		var pkg packageJSON
		if json.Unmarshal(data, &pkg) == nil && pkg.Name != "" && pkg.Version != "" {
			entries = append(entries, entry{pkg.Name, pkg.Version})
		}
	}

	// Actual installed versions from npm/package-lock.json (runtime deps).
	if resolved, err := resolvedVersions("../../npm/package-lock.json"); err == nil {
		for name, ver := range resolved {
			entries = append(entries, entry{name, ver})
		}
	} else {
		log.Printf("warning: npm/package-lock.json: %v", err)
	}

	// Actual installed versions from top-level package-lock.json (dev tooling).
	if resolved, err := resolvedVersions("../../package-lock.json"); err == nil {
		for name, ver := range resolved {
			entries = append(entries, entry{name, ver})
		}
	} else {
		log.Printf("warning: package-lock.json: %v", err)
	}

	// Stable output order.
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Name < entries[j].Name
	})

	var buf strings.Builder
	fmt.Fprintf(&buf, "// Code generated by gen_npm_versions.go; DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "// Generated: %s\n\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(&buf, "package main\n\n")
	fmt.Fprintf(&buf, "func init() {\n")
	for _, e := range entries {
		fmt.Fprintf(&buf, "\tregisterVersion(%q, %q, %q)\n", e.Name, e.Version, "npm")
	}
	fmt.Fprintf(&buf, "}\n")

	if err := os.WriteFile("npm_versions.go", []byte(buf.String()), 0o644); err != nil {
		log.Fatalf("write npm_versions.go: %v", err)
	}
	fmt.Fprintf(os.Stderr, "wrote npm_versions.go (%d entries)\n", len(entries))
}
